infrastructureDefinition:
  name: production-apj-north
  identifier: productionapjnorth
  orgIdentifier: default
  projectIdentifier: default_project
  environmentRef: my_cluster
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: k8s_cluster_try_3
    namespace: production-apj-north
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: false
