apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as needed

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      securityContext:
        runAsUser: 0
      containers:
      - name: sql-server-container
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD 
          value: {{.Values.secret}} #${serviceVariable.secret} #"${values.secret}" #"${stage.variables.secret}"  # Set a strong password for SA account. Highly recommend to modify this before applying
        - name: MSSQL_PID
          value: "Developer"
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: sql-data-volume
          mountPath: /var/opt/mssql
      volumes:
      - name: sql-data-volume
        persistentVolumeClaim:
          claimName: sql-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sql-server-service
spec:
  selector:
    app: sql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  #type: LoadBalancer  # Expose the service outside the cluster
